name: secrete_friend_drawer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  bloc: ^9.1.0
  bloc_test: ^10.0.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/plane.png"
  background_color: "#FFFFFF"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/plane.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
