android-pixel-4:
  app: build/app/outputs/flutter-apk/app-debug.apk
  test: build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  device:
    model: Pixel4
    version: 30
    locale: en
    orientation: portrait
